spring:
  application:
    name: task_app_api

  rabbitmq:
    addresses: rabbitmq
    username: guest
    password: guest

server:
  port: 8081
  servlet:
    context-path: /api

config:
  active:
    on-profile: dev